---
# tasks file for postgresql

# Install PostgreSQL
- name: "[POSTGRESQL] Install PostgreSQL"
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    postgresql
    psycopg2
  tags:
    - postgresql

- copy:
    src: "{{ item }}"
    dest: "/etc/postgresql/9.6/main/{{ item }}"
    owner: postgres
    group: postgres
  with_items:
    - pg_hba.conf
    - postgresql.conf

# Create a new schema {{ postgresql_schema_name }} 
#- postgresql_schema:
#    name: "{{ postgresql_schema_name }}"
#  tags:
#    - postgresql

# Create a new user ({{ postgresql_user }}) for {{ postgresql_schema_name }} 
#- postgresql_user:
#    db: "{{ postgresql_schema_name }}"
#    name: "{{ postgresql_user }}"
#    password: "{{ postgresql_password }}"
#    priv: ALL
#  tags:
#    - postgresql