---
# tasks file for postgresql

# Install PostgreSQL
- name: "[POSTGRESQL] Install PostgreSQL"
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - postgresql
    - python-psycopg2
  tags:
    - postgresql

- name: "[POSTGRESQL] Configure PostgreSQL"
  copy:
    src: "{{ item }}"
    dest: "/etc/postgresql/9.6/main/{{ item }}"
    owner: postgres
    group: postgres
  with_items:
    - pg_hba.conf
    - postgresql.conf
  notify:
    - "[POSTGRESQL] Restart PostgreSQL"
  tags:
    - postgresql
